### PR TITLE
Minor spelling - added codespell, pre-commit isort issue, poetry to setuptools

### PR DESCRIPTION
**Pull request by IndexSeek**
I have started using this package as a pre-commit hook, and I really enjoy it. 

There are a few things I would like to do for future improvements, such as certain returns bringing back the hex value of object memory addresses causing what could be considered unnecessary diffs. I will create an issue with an example of what I'm discussing soon. :) 

- With CI, I've been using [codespell](https://github.com/codespell-project/codespell) a good bit, and I think it could be worth adding to this repo, and I added a pre-commit hook for it. I caught a few minor typos with it, and I found one manually:
  - direcotory ==> directory
  - PiPy ===> PyPI
- When running pre-commit, I received cryptic errors with isort bubbling up from Poetry. I rewrote the pyproject file to use a setuptools-based approach, only to realize that the issue was with a specific dependency that isort was using, causing a poetry compatibility issue. I was able to resolve the issue by updating the pre-commit hook to a newer version of isort, but I left the pyproject adjustment as-is if using setuptools instead would be viable and updated the CONTRIBUTING file to correspond to setuptools instead.

### CODE REVIEW

**Comment by murilo-cunha** [comment]
Hi, thanks for the PR! Glad you like it!

>  I will create an issue with an example of what I'm discussing soon. :)

Looking forward to it! 💪 

> using [codespell](https://github.com/codespell-project/codespell) a good bit

Thanks! I think it'd be a good addition indeed.

> I was able to resolve the issue by updating the pre-commit hook to a newer version of isort

That's great! I find it a bit weird though that errors would bubble up from Poetry. I was also under the impression that `pre-commit` would create a separate virtual environment for each hook similar to what `pipx` does...

In any case, wouldn't hurt to bump isort version here

> using setuptools instead would be viable

As of now, the only blocker for this would be that we're currently bumping the version and publishing in the CI, and we [use poetry for that](https://github.com/datarootsio/databooks/blob/main/.github/workflows/publish.yml#L41).

I've considered switching to `hatch` but it seemed like a bit of an overkill since nothing's broken at the moment

**Comment by IndexSeek** [comment]
> That's great! I find it a bit weird though that errors would bubble up from Poetry. I was also under the impression that `pre-commit` would create a separate virtual environment for each hook similar to what `pipx` does...

It was very strange how the Poetry/pre-commit issue was bubbling up; here's a screenshot; it seems to be from an underlying dependency. 

image

> As of now, the only blocker for this would be that we're currently bumping the version and publishing in the CI, and we [use poetry for that](https://github.com/datarootsio/databooks/blob/main/.github/workflows/publish.yml#L41).

> I've considered switching to hatch but it seemed like a bit of an overkill since nothing's broken at the moment

I reverted that commit, I think it was just a weird pre-commit thing, makes sense to keep things as they are for now! 👍

**Comment by murilo-cunha** [comment]
Thanks for the work and the changes!!

So... after a lot of struggling with the CI, I've made some changes. Could you check that this isort version works @IndexSeek ?

I've had to bump the isort version down (to `5.11.5`), as `5.12.0` does not support `python 3.7`. I'm planning to drop support in the end of June when [it's sunsetted](https://devguide.python.org/versions/#supported-versions). I also think that dropping 3.7 support is a bigger change that should go in another PR

This isort version should still [fix incompatibilities with the latest poetry version](https://github.com/PyCQA/isort/releases/tag/5.11.5). On another note, did you install poetry with `pipx` or alike? Another hypothesis I had is that if you install globally there may be some issues.

I've updated the poetry version in CI and updated the lock - the issue was related to some dependencies after installing poetry, and tried to use the venv in CI.

If it works on your end, I'll be happy to merge it!

Thanks again!

**Comment by IndexSeek** [comment]
> Thanks for the work and the changes!!

Very glad to help, looking forward to being able to contribute to a more "featureful" PR soon. Thank you for collaborating on the effort!

> So... after a lot of struggling with the CI, I've made some changes. Could you check that this isort version works @IndexSeek ?

It is working perfect for me!

> I've had to bump the isort version down (to `5.11.5`), as `5.12.0` does not support `python 3.7`. I'm planning to drop support in the end of June when [it's sunsetted](https://devguide.python.org/versions/#supported-versions). I also think that dropping 3.7 support is a bigger change that should go in another PR

Very good catch, I didn't realize 5.12 dropped support for 3.7. 

> This isort version should still [fix incompatibilities with the latest poetry version](https://github.com/PyCQA/isort/releases/tag/5.11.5). On another note, did you install poetry with `pipx` or alike? Another hypothesis I had is that if you install globally there may be some issues.

It was a global installation, I bet that is likely the problem with it. It's been awhile since I configured it, I'll try reconfiguring it all again soon with the latest version and try `pipx`. Admittedly, I've never used that before, so looking forward to checking it out!

> If it works on your end, I'll be happy to merge it!

All worked for me, I think we're good to go with a merge.

**Comment by murilo-cunha** [comment]
Nice! Thanks!

> Very good catch, I didn't realize 5.12 dropped support for 3.7.

Yeah me neither, but CI was complaining 😅 

> looking forward to checking it out!

I quite like it. Feel free to ping me if you have any questions :)

> good to go with a merge.

🚀 🚀

**Review by murilo-cunha — APPROVED** [review]

**Pull request merged**
